### ISSUE TITLE
[BUG] BUNKRR scraping fails on albums and single files with Unknown

### ISSUE THREAD

**Issue by yusufbromack** [jbsparrow/CyberDropDownloader#183] opened 2024-10-20 04:34 UTC
**Description of the bug**
When attempting to download from bunkrr, cyberdrop-dl-patched fails with "Unknown" scraping error

**To Help Reproduce**
Example Album: [https://bunkr.si/a/hupsMraw](https://bunkr.si/a/hupsMraw)
Example Single File: [https://bunkr.ax/v/kLTwXsky3udi0](https://bunkr.ax/v/kLTwXsky3udi0)

**Screenshots**
Screenshot not necessary, it's just an Unknown scraping error

**Setup Information**
 - OS: Windows 10, Python 3.11
 - Cyberdrop Downloader Version # cyberdrop-dl-patched 5.6.52

**Downloader.log file**
For Album: [downloader.log](https://github.com/user-attachments/files/17448896/downloader.log)
For Single File: [downloader.log](https://github.com/user-attachments/files/17448890/downloader.log)

**Additional context**
Seems to be just a simple scraping reconfiguration issue; since bunkrr changed their layout, the old element classes and attributes aren't used for the titles and download links etc.

**Comment by NTFSvolume** [comment] 2024-10-20 05:04
Duplicate of #176. Fix will be implemented in the next release

**Comment by yusufbromack** [comment] 2024-10-20 05:24
Gotcha, although #176  is describing 404 errors and this one is throwing "unknown"; you can't scrape a site if you can't get to it :P

**Comment by crazydavebacon** [comment] 2024-10-20 08:52
> Duplicate of #176. Fix will be implemented in the next release

Problem is, this was marked as fixed over 12 hours ago. and it still doesn't work...I applied the fix in your reply on the last one, saved the .py file, still doesn't work. So changing what you did didn't help. What will change in a new release that you didn't change in that file?

Sorry if this is dumb, but Im not fluent in code and stull thats why I am asking

**Comment by vajdao** [comment] 2024-10-20 21:45
`Constructor parameter should be str`

having something similiar error, here's my log: https://gist.github.com/vajdao/4aef1dc412f373b54647742f50aafa1f

I remember I had something index or out of range traceback too (on bunkrr links), but that log got overwritten since then because uhh.. doing some **MASS**ive scraping over here xD

<details>
  <summary>Links 🤭 (NSFW obviously) all working in browser :</summary>


https://cdn.bunkr.ru/Persephone-Pink-4-EeYGB9Pu.mp4
https://cdn10.bunkr.ru/Daddyslittlegirl-Cosplay-Slut-With-Cream-Pie-ronDVTFs.mp4
https://cdn10.bunkr.ru/Daddyslittlegirl-Cum-On-My-Ass-Joi-cczLhXo9.mp4
https://cdn10.bunkr.ru/Daddyslittlegirl-Oiling-Up-My-Fat-Ass-OSvr5XL8.mp4
https://cdn10.bunkr.ru/Daddyslittlegirl-Watching-Your-Little-Sister-Strip-Crcu6eqz.mp4
https://cdn8.bunkr.ru/9cae23c1-771b-44f7-a1d6-a6c028e3f74b-axUBXdF1.mp4
https://cdn8.bunkr.ru/OnlyFans-w9XntrAU.mp4
https://cdn8.bunkr.ru/cbd07932-ca65-4ce2-b8ba-816c48feb60c-ml53nRiW.mp4
https://cdn9.bunkr.ru/0he2r2mcu3yb2t2ajqpuq_source-dQQ5xZJq.mp4
 </details>

**Closed** 2024-10-21 01:11 UTC
Labels: bug
