### ISSUE TITLE
[BUG] sqlite3.IntegrityError: UNIQUE constraint failed: files.folder, files.download_filename

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#390] opened 2024-12-24 03:14 UTC
### I have taken steps to troubleshoot my issue first

- [X] I'm using the latest version of `cyberdrop-dl-patched`
- [X] I’ve read the wiki and my issue isn’t already covered.
- [X] I’ve checked existing issues to ensure this hasn’t been reported already.

### Describe the bug

I was using 5.7.2.post4 for a while, and everything was fine. Upgraded to 6.0.0.

First time I launched CDL with my usual command line parameters it said that `--output-folder` is not a valid parameter. Looked through the wiki, replaced it with `--download-folder`.

Now there are no more errors about parameters, but CDL still fails almost immediately upon launch with:

```
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\main.py", line 264, in <module>
    main()
    ~~~~^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\main.py", line 250, in main
    manager = startup()
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\main.py", line 49, in startup
    manager.startup()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\managers\manager.py", line 74, in startup
    self.first_time_setup.transfer_v5_to_new_hashtable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\utils\transfer\db_setup.py", line 28, in transfer_v5_to_new_hashtable
    transfer_from_old_hash_table(db_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\utils\transfer\transfer_hash_db.py", line 63, in transfer_from_old_hash_table
    cursor.executemany(
    ~~~~~~~~~~~~~~~~~~^
        "INSERT INTO files (folder, download_filename, original_filename, file_size, referer, date) VALUES (?, ?, ?, ?, ?, ?);",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        data_to_insert_files,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
sqlite3.IntegrityError: UNIQUE constraint failed: files.folder, files.download_filename
```

### Desired result

I guess it should work

### Steps to help reproduce the behavior

see above

### Relevant logs

n/a

### Operating system/environment

Windows 11 24H2

### Python Version

3.13.496.0

### Cyberdrop-DL version

6.0.0

**Comment by NTFSvolume** [comment] 2024-12-24 04:22
When this is fixed, a new version will be released. You should have a backup of the old database at `AppData/Cache/cyberdrop_v5_<DATETIME>.bak.db`

Before you run the new version with the fix, delete the current database (`cyberdrop.db`) and rename the backup to `cyberdrop.db`

**Comment by baccccccc** [comment] 2024-12-24 04:33
Thanks. I made the changes from !392 manually, and it seemed to help.

Just so you know (and maybe include this into documentation at some point) it then started complaining about my FlareSolverr address:

```
ERROR: found 1 error parsing GlobalSettings from C:\Users\artem\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\Configs\global_settings.yaml

Value of 'General.flaresolverr' is invalid:
  Input should be a valid URL, relative URL without a base (input_value='127.0.0.1:8191', input_type='url_parsing')

Read the documentation for guidance on how to resolve this error: https://script-ware.gitbook.io/cyberdrop-dl/reference/configuration-options
Please note, this is not a bug. Do not open issues related to this
```

I had to replace `127.0.0.1:8191` with `http://127.0.0.1:8191` and it helped.

**Comment by NTFSvolume** [comment] 2024-12-24 05:18
That's intentional. The wiki was updated before v6 release to mention that it should be a full scheme HTTP URL.

https://script-ware.gitbook.io/cyberdrop-dl/reference/configuration-options/global-settings/general#flaresolverr

**Comment by baccccccc** [comment] 2024-12-24 06:08
on a similar note, I just figured that I had to rename my cookie files from `domain.txt` to `domain.tld.txt`. I see it's kinda documented, in the sense that if you look this up, the updated requirement is there. But my point it, it would probably help to list all v5 -> v6 changes in one place, such as:

- you have to change `--output-folder` to `--download-folder` (and maybe other paraemters?) if you launch from command line;
- you have to add URL scheme to some settings, such as `General.flaresolverr`;
- you have to rename your cookie files if you rely on them
- who knows what else?

And it probably goes without saying, but huge thank you for taking this project forward, fixing issues quickly and also updating docs. Your input is highly appreciated, and I probably should say it more often :)

**Comment by NTFSvolume** [comment] 2024-12-24 06:47
Those types of changes are documented on the [CHANGELOG](https://github.com/jbsparrow/CyberDropDownloader/blob/master/CHANGELOG.md)

1. The new CLI arguments names are not documented on the changelog, but CDL will show a warning for a few seconds if a deprecated flag was used, alongside the new name.  The problem is that `--output-folder` was not added to the deprecated args. We can fix it for the next patch version.

```shell
<frozen runpy>:198: DeprecationWarning: '--last-forum-post-filename' is deprecated and will be removed in the future. Use '--last-forum-post'
```

2. For config values is not possible to tell the user what they need to change to make the value valid. A full scheme URL was already a valid value on v5.7.2. Some user are using `null` or `None`, others have an empty string or use `localhost` instead of an IP. We can't cover all cases for all config settings, that's why is better to just document want the value _should_ be and then is up to the user to figure out what they need to change.

3. This is the same as the previous point. The user only have to rename the cookie file for some sites, not all of them. The issue was that, in v5, the cookie filename format was inconsistent across all sites. Some sites used the second level domain (like `cyberdrop.txt`) but others used the full primary base domain (like `xxxbunker.com`). Now all sites use the full primary base domain.

4. Any other relevant change should be expected to be added to the changelog. However, there could be oversights since the file is edited manually.

I think for cookies we can throw a log warning if a cookie file name does not match any of the primary base domain of the supported sites, to hint to the user that they should probably change the name

**Closed** 2024-12-24 07:21 UTC
Labels: bug
